export const dataMusic = [
    {
        id: 1,
        title: "Don't Wanna Leave",
        artist: "Jacob Latimore feat. Mulatto",
        genre: "R’n’B",
        img: "1.jpg",
        url: "../assets/tracks/1577032745_jacob-latimore-feat_-mulatto-dont-wanna-leave.mp3",
    },
    {
        id: 2,
        title: "Prblms",
        artist: "6Lack",
        genre: "Rep",
        img: "2.jpg",
        url: "../assets/tracks/6Lack Prblms.mp3",
    },
    {
        id: 3,
        title: "Simfonija 5, Allegro con brio",
        artist: "Ludwig van Beethoven",
        genre: "Classic",
        img: "3.jpg",
        url: "../assets/tracks/betkhoven-simfonija-5-allegro-con-brio.mp3",
    },
    {
        id: 4,
        title: "BIRDS OF A FEATHER",
        artist: "Billie Eilish",
        genre: "Pop",
        img: "4.jpg",
        url: "../assets/tracks/Billie Eilish – BIRDS OF A FEATHER.mp3",
    },
    {
        id: 5,
        title: "Drill Instructor (Short Mix)",
        artist: "Captain Jack",
        genre: "80-90",
        img: "5.jpg",
        url: "../assets/tracks/Captain Jack - Drill Instructor (Short Mix).mp3",
    },
    {
        id: 6,
        title: "River Flows in You",
        artist: "Caterina Barontini",
        genre: "Classic",
        img: "6.jpg",
        url: "../assets/tracks/Caterina Barontini - River Flows in You.mp3",
    },
    {
        id: 7,
        title: "Yellow",
        artist: "Coldplay",
        genre: "Pop",
        img: "7.jpg",
        url: "../assets/tracks/Coldplay-Yellow.mp3",
    },
    {
        id: 8,
        title: "Hey Everybody (Radio Edit)",
        artist: "DJ Company",
        genre: "80-90",
        img: "8.jpg",
        url: "../assets/tracks/DJ_Company-Hey_Everybody_Radio_Edit-world76.spcs.bio.mp3",
    },
    {
        id: 9,
        title: "Rhapsody In Blue",
        artist: "George Gershwin",
        genre: "Classic",
        img: "9.jpg",
        url: "../assets/tracks/George Gershwin – Rhapsody In Blue.mp3",
    },
    {
        id: 10,
        title: "Feel Good Inc",
        artist: "Gorillaz",
        genre: "Pop",
        img: "10.jpg",
        url: "../assets/tracks/Gorillaz - Feel Good Inc (1).mp3",
    },
    {
        id: 11,
        title: "Feel Good Inc",
        artist: "Gorillaz",
        genre: "Pop",
        img: "11.jpg",
        url: "../assets/tracks/Gorillaz - Feel Good Inc.mp3",
    },
    {
        id: 12,
        title: "Also Sprach Zarathustra - Fanfare",
        artist: "Johann Strauss Jr.",
        genre: "Classic",
        img: "12.jpg",
        url: "../assets/tracks/johann-strauss-jr-also-sprach-zarathustra.mp3",
    },
    {
        id: 13,
        title: "After Hours",
        artist: "Kehlani",
        genre: "R’n’B",
        img: "13.jpg",
        url: "../assets/tracks/Kehlani - After Hours.mp3",
    },
    {
        id: 14,
        title: "Poker Face",
        artist: "Lady Gaga",
        genre: "Pop",
        img: "14.jpg",
        url: "../assets/tracks/Lady Gaga - Poker Face.mp3",
    },
    {
        id: 15,
        title: "Calling My Phone",
        artist: "Lil Tjay, 6LACK",
        genre: "Rep",
        img: "15.jpg",
        url: "../assets/tracks/Lil_Tjay_6LACK_-_Calling_My_Phone.mp3",
    },
    {
        id: 16,
        title: "SUPERMODEL",
        artist: "Måneskin",
        genre: "Rock",
        img: "16.jpg",
        url: "../assets/tracks/måneskin-supermodel.mp3",
    },
    {
        {
            id: 17,
            title: "Return of the Mack",
            artist: "Mark Morrison",
            genre: "80-90",
            img: "17.jpg",
            url: "../assets/tracks/mark-morrison-return-of-the-mack.mp3",
        },
        {
            id: 18,
            title: "No More (I Can't Stand It) (Airplay Mix)",
            artist: "MAXX",
            genre: "80-90",
            img: "18.jpg",
            url: "../assets/tracks/MAXX - No More (I Can't Stand It) (Airplay Mix).mp3",
        },
        {
            id: 19,
            title: "Simfonija 40",
            artist: "Wolfgang Amadeus Mozart",
            genre: "Classic",
            img: "19.jpg",
            url: "../assets/tracks/mocart-simfonija-40.mp3",
        },
        {
            id: 20,
            title: "Don't Get Me Wrong",
            artist: "The Pretenders",
            genre: "Rock",
            img: "20.jpg",
            url: "../assets/tracks/Pretenders - Don't Get Me Wrong (megapesni.fm).mp3",
        },
        {
            id: 21,
            title: "Torpedo",
            artist: "Rae Sremmurd",
            genre: "Rep",
            img: "21.jpg",
            url: "../assets/tracks/Rae Sremmurd - Torpedo.mp3",
        },
        {
            id: 22,
            title: "I Love You Boy",
            artist: "Russ",
            genre: "Rep",
            img: "22.jpg",
            url: "../assets/tracks/russ-i-love-you-boy.mp3",
        },
        {
            id: 23,
            title: "Shut Up and Drive",
            artist: "Rihanna",
            genre: "Rock",
            img: "23.jpg",
            url: "../assets/tracks/Rihanna Shut Up And Drive.mp3",
        },
        {
            id: 24,
            title: "It's Like That",
            artist: "Run DMC",
            genre: "80-90",
            img: "24.jpg",
            url: "../assets/tracks/Run DMC - It's Like That.mp3",
        },
        {
            id: 25,
            title: "Black Summer",
            artist: "Red Hot Chili Peppers",
            genre: "Rock",
            img: "25.jpg",
            url: "../assets/tracks/Red Hot Chili Peppers – Black Summer.mp3",
        },
        {
            id: 26,
            title: "Wake Up",
            artist: "Skylar Blatt feat. Chris Brown",
            genre: "R’n’B",
            img: "26.jpg",
            url: "../assets/tracks/Skylar Blatt feat. Chris Brown - Wake Up.mp3",
        },
        {
            id: 27,
            title: "Make It All Right",
            artist: "The Offspring",
            genre: "Rock",
            img: "27.jpg",
            url: "../assets/tracks/The Offspring - Make It All Right.mp3",
        },
        {
            id: 28,
            title: "HOLIDAY",
            artist: "Turnstile",
            genre: "Rock",
            img: "28.jpg",
            url: "../assets/tracks/Turnstile-HOLIDAY-world76.spcs.bio.mp3",
        },
        {
            id: 29,
            title: "Jump",
            artist: "Tyla, Gunna, Skillibeng",
            genre: "R’n’B",
            img: "29.jpg",
            url: "../assets/tracks/Tyla, Gunna, Skillibeng - Jump.mp3",
        },
        {
            id: 29,
            title: "Симфонія № 40",
            artist: "Вольфганг Амадей Моцарт",
            genre: "Classic",
            img: "29.jpg",
            url : "../assets/tracks/twenty one pilots - doubt.mp3",
        }

    ]